language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source

script:
  - phpunit

notifications:
  email:
    recipients:
      - apt142@gmail.com
    on_success: change
    on_failure: always
